In [34]:
import numpy as np
import pandas as pd

In [35]:
coins = pd.read_csv('coins_200.csv')

In [36]:
coins.head()

,Rank,Name,Symbol,MainLink,HistoricalLink,Git_hub,Tags
0,1,Bitcoin,BTC,https://coinmarketcap.com/currencies/bitcoin/,https://coinmarketcap.com/currencies/bitcoin/h...,https://github.com/bitcoin/bitcoin,"Mineable,PoW,SHA-256"
1,2,Ethereum,ETH,https://coinmarketcap.com/currencies/ethereum/,https://coinmarketcap.com/currencies/ethereum/...,https://github.com/ethereum/wiki/wiki/White-Paper,"PoS,Smart Contracts,Ethereum Ecosystem"
2,3,Tether USDt,USDT,https://coinmarketcap.com/currencies/tether/,https://coinmarketcap.com/currencies/tether/hi...,NaN,"Payments,Stablecoin,Asset-Backed Stablecoin"
3,4,BNB,BNB,https://coinmarketcap.com/currencies/bnb/,https://coinmarketcap.com/currencies/bnb/histo...,https://github.com/bnb-chain,"Marketplace,Centralized Exchange (CEX) Token,P..."
4,5,XRP,XRP,https://coinmarketcap.com/currencies/xrp/,https://coinmarketcap.com/currencies/xrp/histo...,https://github.com/ripple/rippled,"Medium of Exchange,Enterprise Solutions,Arring..."

Making table Coins_information

In [37]:
coins_information = pd.DataFrame()

for i in range(coins.shape[0]):
    coin_name = coins["Name"][i]
    tail_of_csv_file_name = "_9_3_2022-9_3_2023_historical_data_coinmarketcap.csv"
    csv_name = coin_name + tail_of_csv_file_name 
    coin_detail = pd.read_csv(csv_name)
    #adding symbol 
    symbol = coins["Symbol"][i]
    symbol_col =[symbol for j in range(coin_detail.shape[0])] 
    coin_detail.insert(loc = 0,
                       column = "Symbol",
                       value = symbol_col)
    coins_information = pd.concat([coins_information ,coin_detail])

coins_information

,Symbol,timeOpen;timeClose;timeHigh;timeLow;open;high;low;close;volume;marketCap;timestamp
0,BTC,"2023-09-02T00:00:00.000Z;""2023-09-02T23:59:59...."
1,BTC,"2023-09-01T00:00:00.000Z;""2023-09-01T23:59:59...."
2,BTC,"2023-08-31T00:00:00.000Z;""2023-08-31T23:59:59...."
3,BTC,"2023-08-30T00:00:00.000Z;""2023-08-30T23:59:59...."
4,BTC,"2023-08-29T00:00:00.000Z;""2023-08-29T23:59:59...."
...,...,...
359,AMP,"2022-09-08T00:00:00.000Z;""2022-09-08T23:59:59...."
360,AMP,"2022-09-07T00:00:00.000Z;""2022-09-07T23:59:59...."
361,AMP,"2022-09-06T00:00:00.000Z;""2022-09-06T23:59:59...."
362,AMP,"2022-09-05T00:00:00.000Z;""2022-09-05T23:59:59...."
363,AMP,"2022-09-04T00:00:00.000Z;""2022-09-04T23:59:59...."

Making table Coins200

In [38]:
Coins200 = coins[["Rank","Name","Symbol","MainLink","HistoricalLink","Git_hub"]]
Coins200

,Rank,Name,Symbol,MainLink,HistoricalLink,Git_hub
0,1,Bitcoin,BTC,https://coinmarketcap.com/currencies/bitcoin/,https://coinmarketcap.com/currencies/bitcoin/h...,https://github.com/bitcoin/bitcoin
1,2,Ethereum,ETH,https://coinmarketcap.com/currencies/ethereum/,https://coinmarketcap.com/currencies/ethereum/...,https://github.com/ethereum/wiki/wiki/White-Paper
2,3,Tether USDt,USDT,https://coinmarketcap.com/currencies/tether/,https://coinmarketcap.com/currencies/tether/hi...,NaN
3,4,BNB,BNB,https://coinmarketcap.com/currencies/bnb/,https://coinmarketcap.com/currencies/bnb/histo...,https://github.com/bnb-chain
4,5,XRP,XRP,https://coinmarketcap.com/currencies/xrp/,https://coinmarketcap.com/currencies/xrp/histo...,https://github.com/ripple/rippled
...,...,...,...,...,...,...
195,196,PlayDapp,PLA,https://coinmarketcap.com/currencies/playdapp/,https://coinmarketcap.com/currencies/playdapp/...,https://github.com/playdapp
196,197,Pundi X (New),PUNDIX,https://coinmarketcap.com/currencies/pundix-new/,https://coinmarketcap.com/currencies/pundix-ne...,NaN
197,198,Vulcan Forged PYR,PYR,https://coinmarketcap.com/currencies/vulcan-fo...,https://coinmarketcap.com/currencies/vulcan-fo...,NaN
198,199,Status,SNT,https://coinmarketcap.com/currencies/status/,https://coinmarketcap.com/currencies/status/hi...,https://github.com/status-im
199,200,Amp,AMP,https://coinmarketcap.com/currencies/amp/,https://coinmarketcap.com/currencies/amp/histo...,https://github.com/amptoken

Making table Tags

In [39]:
Tags = pd.read_csv('Tags.csv')
Tags

     Tags_Id                        Tags
0          1               AI & Big Data
1          2  Alameda Research Portfolio
2          3      Algorithmic Stablecoin
3          4      Alleged SEC Securities
4          5             Aptos Ecosystem
..       ...                         ...
121      122                         X11
122      123               XDC Ecosystem
123      124            Yield Aggregator
124      125               Yield Farming
125      126       Zero Knowledge Proofs

[126 rows x 2 columns]

Making table coin_tags

In [88]:
coin_tags = pd.DataFrame()
for i in range(coins.shape[0]):
    symbol = coins["Symbol"][i]
    #print(type(coins["Tags"][i]))
    try:
        tags = (coins["Tags"][i]).split(",")
        num_tags = len(tags)
        symbol_col = [symbol for j in range(num_tags)]
        tags_col = list()
        for tag in tags :
            temp = Tags[Tags["Tags"]==tag]
            temp = temp["Tags_Id"]
            tag_id = temp.iloc[0]
            tags_col.append(tag_id)
    except :
        tags_col = ["nan"]
        symbol_col = [symbol]
        

    
    data = {"Symbol":symbol_col,"Tag_Id":tags_col}
    coin_tag = pd.DataFrame(data= data)
    coin_tags = pd.concat([coin_tags,coin_tag])

In [90]:
coin_tags

   Symbol Tag_Id
0     BTC     78
1     BTC     91
2     BTC     99
0     ETH     90
1     ETH    104
..    ...    ...
0     SNT     74
1     SNT     29
2     SNT     95
0     AMP     98
1     AMP      4

[560 rows x 2 columns]