In [1]:
import numpy as np
import pandas as pd
import mysql.connector

In [2]:
coins = pd.read_csv('coins_200.csv')

In [3]:
coins.head()

,Rank,Name,Symbol,MainLink,HistoricalLink,Git_hub,Tags
0,1,Bitcoin,BTC,https://coinmarketcap.com/currencies/bitcoin/,https://coinmarketcap.com/currencies/bitcoin/h...,https://github.com/bitcoin/bitcoin,"Mineable,PoW,SHA-256"
1,2,Ethereum,ETH,https://coinmarketcap.com/currencies/ethereum/,https://coinmarketcap.com/currencies/ethereum/...,https://github.com/ethereum/go-ethereum,"PoS,Smart Contracts,Ethereum Ecosystem"
2,3,Tether USDt,USDT,https://coinmarketcap.com/currencies/tether/,https://coinmarketcap.com/currencies/tether/hi...,NaN,"Payments,Stablecoin,Asset-Backed Stablecoin"
3,4,BNB,BNB,https://coinmarketcap.com/currencies/bnb/,https://coinmarketcap.com/currencies/bnb/histo...,https://github.com/bnb-chain,"Marketplace,Centralized Exchange (CEX) Token,P..."
4,5,XRP,XRP,https://coinmarketcap.com/currencies/xrp/,https://coinmarketcap.com/currencies/xrp/histo...,https://github.com/ripple/rippled,"Medium of Exchange,Enterprise Solutions,Arring..."

In [4]:
coins_information = pd.DataFrame()

for i in range(coins.shape[0]):
    coin_name = coins["Name"][i]
    tail_of_csv_file_name = "_9_3_2022-9_3_2023_historical_data_coinmarketcap.csv"
    csv_name =  "csvs\\" +coin_name + tail_of_csv_file_name 
    coin_detail = pd.read_csv(csv_name , delimiter=";")
    #adding symbol 
    symbol = coins["Symbol"][i]
    symbol_col =[symbol for j in range(coin_detail.shape[0])] 
    coin_detail.insert(loc = 0,
                       column = "Symbol",
                       value = symbol_col)
    coin_detail["circulatingSupply"] =coin_detail["marketCap"]/coin_detail["close"]
    coins_information = pd.concat([coins_information ,coin_detail])


coins_information["circulatingSupply"] =coins_information["marketCap"]/coins_information["close"]
coins_information

,Symbol,timeOpen,timeClose,timeHigh,timeLow,open,high,low,close,volume,marketCap,timestamp,circulatingSupply
0,BTC,2023-09-02T00:00:00.000Z,2023-09-02T23:59:59.999Z,2023-09-02T15:41:00.000Z,2023-09-02T03:22:00.000Z,25800.909609,25970.284489,25753.093847,25868.798140,1.010039e+10,5.037864e+11,2023-09-02T23:59:59.999Z,1.947468e+07
1,BTC,2023-09-01T00:00:00.000Z,2023-09-01T23:59:59.999Z,2023-09-01T12:24:00.000Z,2023-09-01T17:42:00.000Z,25934.020806,26125.869774,25362.609128,25800.724373,1.720286e+10,5.024359e+11,2023-09-01T23:59:59.999Z,1.947371e+07
2,BTC,2023-08-31T00:00:00.000Z,2023-08-31T23:59:59.999Z,2023-08-31T11:43:00.000Z,2023-08-31T21:09:00.000Z,27301.929317,27456.079001,25752.929947,25931.472893,2.018100e+10,5.049576e+11,2023-08-31T23:59:59.999Z,1.947277e+07
3,BTC,2023-08-30T00:00:00.000Z,2023-08-30T23:59:59.999Z,2023-08-30T00:21:00.000Z,2023-08-30T15:04:00.000Z,27726.084034,27760.159397,27069.207425,27297.265348,1.634366e+10,5.315289e+11,2023-08-30T23:59:59.999Z,1.947188e+07
4,BTC,2023-08-29T00:00:00.000Z,2023-08-29T23:59:59.999Z,2023-08-29T16:28:00.000Z,2023-08-29T10:39:00.000Z,26102.485832,28089.338027,25912.628909,27727.393009,2.936839e+10,5.398825e+11,2023-08-29T23:59:59.999Z,1.947109e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,AMP,2022-09-08T00:00:00.000Z,2022-09-08T23:59:59.999Z,2022-09-08T18:30:00.000Z,2022-09-08T13:30:00.000Z,0.005586,0.005695,0.005482,0.005655,7.168563e+06,2.388120e+08,2022-09-08T23:59:59.999Z,4.222770e+10
360,AMP,2022-09-07T00:00:00.000Z,2022-09-07T23:59:59.999Z,2022-09-07T20:34:00.000Z,2022-09-07T05:07:00.000Z,0.005548,0.005750,0.005431,0.005594,6.512543e+06,2.362275e+08,2022-09-07T23:59:59.999Z,4.222770e+10
361,AMP,2022-09-06T00:00:00.000Z,2022-09-06T23:59:59.999Z,2022-09-06T00:59:00.000Z,2022-09-06T22:37:00.000Z,0.005998,0.006069,0.005559,0.005566,7.139461e+06,2.350460e+08,2022-09-06T23:59:59.999Z,4.222770e+10
362,AMP,2022-09-05T00:00:00.000Z,2022-09-05T23:59:59.999Z,2022-09-05T00:08:00.000Z,2022-09-05T19:55:00.000Z,0.006053,0.006109,0.005950,0.005997,3.840475e+06,2.532284e+08,2022-09-05T23:59:59.999Z,4.222770e+10
363,AMP,2022-09-04T00:00:00.000Z,2022-09-04T23:59:59.999Z,2022-09-04T21:16:00.000Z,2022-09-04T10:34:00.000Z,0.006017,0.006075,0.005996,0.006053,3.193905e+06,2.555903e+08,2022-09-04T23:59:59.999Z,4.222770e+10

In [5]:
total_tags = pd.read_csv("main_files\\total_tags.csv")
Coins_links = pd.concat([coins["Symbol"] , total_tags] , axis=1 , join="inner")

In [6]:
Coins_links

,Symbol,Algorithm,Category,Others,Platform,Industry,Self-Reported Tags,no_lable
0,BTC,"PoW,SHA-256","Store Of Value,State Channel,Coinbase Ventures...",Mineable,Bitcoin Ecosystem,NaN,NaN,NaN
1,ETH,PoS,"Smart Contracts,Coinbase Ventures Portfolio,Th...",NaN,"Ethereum Ecosystem,Injective Ecosystem",NaN,NaN,NaN
2,USDT,NaN,"Stablecoin,Asset-Backed Stablecoin,USD Stablecoin",NaN,"Avalanche Ecosystem,Solana Ecosystem,Arbitrum ...",Payments,NaN,NaN
3,BNB,NaN,"Centralized Exchange (CEX) Token,Smart Contrac...",NaN,BNB Chain,"Marketplace,Payments",NaN,NaN
4,XRP,NaN,"Arrington XRP Capital Portfolio,Galaxy Digital...",NaN,NaN,"Medium of Exchange,Enterprise Solutions",NaN,NaN
...,...,...,...,...,...,...,...,...
195,PLA,NaN,Metaverse,NaN,"Ethereum Ecosystem,Polygon Ecosystem",Gaming,NaN,NaN
196,PUNDIX,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,PYR,NaN,"Collectibles & NFTs,Metaverse,DWF Labs Portfolio",NaN,NaN,"Gaming,Entertainment",NaN,NaN
198,SNT,NaN,"Privacy,Fabric Ventures Portfolio,Kenetic Capi...",NaN,NaN,"Media,Content Creation",NaN,NaN
199,AMP,NaN,NaN,NaN,NaN,NaN,NaN,"SEC Security Token,Alleged SEC Securities"

In [7]:
Coins200 = coins[["Rank","Name","Symbol","MainLink","HistoricalLink"]]
Coins200

,Rank,Name,Symbol,MainLink,HistoricalLink
0,1,Bitcoin,BTC,https://coinmarketcap.com/currencies/bitcoin/,https://coinmarketcap.com/currencies/bitcoin/h...
1,2,Ethereum,ETH,https://coinmarketcap.com/currencies/ethereum/,https://coinmarketcap.com/currencies/ethereum/...
2,3,Tether USDt,USDT,https://coinmarketcap.com/currencies/tether/,https://coinmarketcap.com/currencies/tether/hi...
3,4,BNB,BNB,https://coinmarketcap.com/currencies/bnb/,https://coinmarketcap.com/currencies/bnb/histo...
4,5,XRP,XRP,https://coinmarketcap.com/currencies/xrp/,https://coinmarketcap.com/currencies/xrp/histo...
...,...,...,...,...,...
195,196,PlayDapp,PLA,https://coinmarketcap.com/currencies/playdapp/,https://coinmarketcap.com/currencies/playdapp/...
196,197,Pundi X (New),PUNDIX,https://coinmarketcap.com/currencies/pundix-new/,https://coinmarketcap.com/currencies/pundix-ne...
197,198,Vulcan Forged PYR,PYR,https://coinmarketcap.com/currencies/vulcan-fo...,https://coinmarketcap.com/currencies/vulcan-fo...
198,199,Status,SNT,https://coinmarketcap.com/currencies/status/,https://coinmarketcap.com/currencies/status/hi...
199,200,Amp,AMP,https://coinmarketcap.com/currencies/amp/,https://coinmarketcap.com/currencies/amp/histo...

In [8]:
total_links = pd.read_csv("main_files\\total_links.csv")
Coins_links = pd.concat([coins["Symbol"] , total_links] , axis=1 , join="inner")
Coins_links

,Symbol,Website,Whitepaper,GitHub,Reddit,BNB Smart Chain (BEP20): 0x2170...f933f8,𝕏Twitter,Chat,CertiK,Fairyproof,...,BNB Smart Chain (BEP20): 0xd41f...ba5dfb,SEI: usei,Solana: hntyVP...1oxWux,Celo: 0x471e...78a438,Salus,Tron20: TCFLL5...mWZZy9,Waves: WAVES,Arbitrum: 0x539b...F60342,Klaytn: 0x02cb...ad51aa,BNB Beacon Chain (BEP2): TOMOB-4BC
0,BTC,https://bitcoin.org/,https://bitcoin.org/bitcoin.pdf,https://github.com/bitcoin/bitcoin,https://reddit.com/r/bitcoin,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ETH,NaN,https://github.com/ethereum/wiki/wiki/White-Paper,https://github.com/ethereum/go-ethereum,https://reddit.com/r/ethereum,https://bscscan.com/token/0x2170ed0880ac9a755f...,https://twitter.com/ethereum,https://gitter.im/orgs/ethereum/rooms,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USDT,https://tether.to,https://tether.to/wp-content/uploads/2016/06/T...,NaN,NaN,NaN,https://twitter.com/tether_to,https://t.me/OfficialTether,https://cmc.certik-skynet.com/redirect?project...,https://fairyproof.com/report/Tether,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BNB,https://bnbchain.org/en,NaN,https://github.com/bnb-chain,https://reddit.com/r/bnbchainofficial,NaN,https://twitter.com/bnbchain,NaN,https://cmc.certik-skynet.com/redirect?project...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,XRP,https://xrpl.org/,https://ripple.com/files/ripple_consensus_whit...,https://github.com/ripple/rippled,https://reddit.com/r/ripple,NaN,https://twitter.com/Ripple,NaN,https://cmc.certik-skynet.com/redirect?project...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,PLA,https://playdapp.io,https://images.playdapp.com/playdapp-homepage/...,https://github.com/playdapp,NaN,NaN,https://twitter.com/playdapp_io,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,PUNDIX,https://pundix.com/,https://pundix.com/pdf/PundiX_Whitepaper_EN_Ve...,NaN,NaN,NaN,https://twitter.com/PundiXLabs,https://t.me/pundix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,PYR,https://vulcanforged.com/,https://vulcanforged.com/public/assets/fronten...,NaN,https://reddit.com/r/vulcanforged,NaN,https://twitter.com/VulcanForged,https://t.me/VeriArti,https://cmc.certik-skynet.com/redirect?project...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,SNT,http://status.im/,https://status.im/whitepaper.pdf,https://github.com/status-im,https://reddit.com/r/statusim,NaN,https://twitter.com/ethstatus,https://join.status.im/status,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,AMP,https://amptoken.org,https://docs.amptoken.org/about/whitepaper,https://github.com/amptoken,https://reddit.com/r/amptoken,NaN,https://twitter.com/amptoken,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
set_tags = set()
for i in range(total_tags.shape[0]):
    for j in range(total_tags.shape[1]):
        if type(total_tags.iloc[i,j]) != str :
            continue
        s = total_tags.iloc[i,j]
        s = s.split(',')
        set_tags = set_tags.union(set(s))

In [10]:
set_tags = sorted(list(set_tags))
data = {'Tag_Id':[i for i in range(1,len(set_tags)+1)],
        'Tag':set_tags}

all_tags = pd.DataFrame(data)
all_tags.to_csv("main_files\\all_tags.csv",index= False)

In [11]:
all_tags

     Tag_Id                         Tag
0         1     1Confirmation Portfolio
1         2               AI & Big Data
2         3                         AMM
3         4  Alameda Research Portfolio
4         5          Algorand Ecosystem
..      ...                         ...
188     189            Yield Aggregator
189     190               Yield Farming
190     191       Zero Knowledge Proofs
191     192           Zilliqa Ecosystem
192     193              a16z Portfolio

[193 rows x 2 columns]

In [12]:
list_category = list(total_tags.columns)
data = {'Category_Id':[i for i in range(1,len(list_category)+1)],
        'Category':list_category}

category = pd.DataFrame(data)
category.to_csv('main_files\\category.csv',index = False)

In [13]:
coin_tags = pd.DataFrame()
for i in range(coins.shape[0]):
    symbol = coins["Symbol"][i]
    num_tags = 0
    tags_col =list()
    for j in total_tags.iloc[i]:
        if type(j)==str :
            
            tags = j.split(',')
            num_tags+=len(tags)
            for tag in tags :
                temp = all_tags[all_tags["Tag"]==tag]
                temp = temp["Tag_Id"]
                tag_id = temp.iloc[0]
                tags_col.append(tag_id)
    if num_tags >0 :
        symbol_col = [symbol for z in range(num_tags)]
    else :
        tags_col = ["nan"]
        symbol_col = [symbol]
    

    data = {"Symbol":symbol_col,"Tag_Id":tags_col}
    coin_tag = pd.DataFrame(data= data)
    coin_tags = pd.concat([coin_tags,coin_tag])
    

coin_tags

   Symbol Tag_Id
0     BTC    138
1     BTC    152
2     BTC    167
3     BTC    165
4     BTC     36
..    ...    ...
2     SNT     99
3     SNT    113
4     SNT     40
0     AMP    150
1     AMP      7

[1600 rows x 2 columns]

In [16]:
languages = pd.read_csv('main_files\\languages.csv')
languages.head()

   Language_Id          Language
0            1      Contributors
1            2          Assembly
2            3                 C
3            4                C#
4            5               C++

In [17]:
github_info = pd.read_csv("main_files\\github_info.csv")
github_info

,stars,forks,C++,Python,C,M4,Shell,Makefile,Other,Go,...,Reason,Standard ML,PEG.js,Erlang,Contributors,tworec,Pact,Smarty,Vue,Rich Text Format
0,71.3k,35.6k,65.6%,19.5%,10.7%,1.3%,1.0%,0.9%,1.0%,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43.6k,18.4k,NaN,NaN,5.1%,NaN,NaN,NaN,1.0%,89.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.4k,1.5k,73.8%,NaN,24.0%,NaN,0.3%,NaN,0.9%,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
coins_ForksStars = pd.concat([coins["Symbol"] , github_info[["stars","forks"]] ], axis=1 , join="inner")
coins_ForksStars

     Symbol  stars  forks
0       BTC  71.3k  35.6k
1       ETH  43.6k  18.4k
2      USDT    NaN    NaN
3       BNB    NaN    NaN
4       XRP   4.4k   1.5k
..      ...    ...    ...
195     PLA    NaN    NaN
196  PUNDIX    NaN    NaN
197     PYR    NaN    NaN
198     SNT    NaN    NaN
199     AMP    NaN    NaN

[200 rows x 3 columns]

In [19]:
coin_languages = pd.DataFrame()
for i in range(coins.shape[0]):
    symbol = coins["Symbol"][i]
    num_languages = 0
    languages_col =list()
    lan_per_col = list()
    
    for lan in languages["Language"]:
        percent = github_info[lan].iloc[i]
        if type(percent)!=str :
            continue
        temp = languages[languages["Language"]==lan]
        temp = temp["Language_Id"]
        lan_id = temp.iloc[0]
        languages_col.append(lan_id)
        lan_per_col.append(percent)
        
        num_languages += 1
    
    if num_languages >0 :
        symbol_col = [symbol for z in range(num_languages)]
    else :
        
        languages_col = ["nan"]
        symbol_col = [symbol]
        lan_per_col = ["nan"]
    
    data = {"Symbol":symbol_col,"Language_Id":languages_col , "Percentage":lan_per_col }
    coin_language = pd.DataFrame(data= data)
    coin_languages = pd.concat([coin_languages,coin_language])
    

coin_languages

    Symbol Language_Id Percentage
0      BTC           3      10.7%
1      BTC           5      65.6%
2      BTC          16       1.3%
3      BTC          17       0.9%
4      BTC          20       1.0%
..     ...         ...        ...
0      PLA         nan        nan
0   PUNDIX         nan        nan
0      PYR         nan        nan
0      SNT         nan        nan
0      AMP         nan        nan

[459 rows x 3 columns]

In [20]:
#connect to mysql database

my_user = 'iliyatu' #enter your username of mysql server
my_password = '1123581321' # enter your pass
my_database = 'coinmarket_extra' # enter your db you want to create

yourDB = mysql.connector.connect(user = my_user,
                                 
                                 password = my_password,
                                 auth_plugin='mysql_native_password'
                                )

print('__ Please Wait !')



cursor = yourDB.cursor()
cursor.execute('CREATE DATABASE %s'%(my_database))
cursor.execute('USE %s' % my_database)

print('__ Done !')

__ Please Wait !
__ Done !

In [21]:
cursor.execute("CREATE TABLE IF NOT EXISTS coins200 (Ra int, Name varchar(60), Symbol varchar(60) PRIMARY KEY , MainLink varchar(255) , HistoricalLink varchar(255) )")
cursor.execute("CREATE TABLE IF NOT EXISTS tags (Tag_Id INT PRIMARY KEY , Tag VARCHAR(255)  )")
cursor.execute("CREATE TABLE IF NOT EXISTS coin_tags (Symbol VARCHAR(60),Tag_Id INT , FOREIGN KEY (Symbol) REFERENCES coins200(Symbol) )")
cursor.execute("CREATE TABLE IF NOT EXISTS coins_information (Symbol varchar(60) , timeOpen varchar(255), timeClose varchar(255), timeHigh varchar(255), timeLow varchar(255), open float, high float , low float, close float, volume float, marketCap float, timestamp varchar(255),circulatingSupply float , FOREIGN KEY (Symbol) REFERENCES coins200(Symbol) )")

print('__ Done !')

__ Done !

In [22]:
cursor.execute("CREATE TABLE IF NOT EXISTS category (Category_Id INT PRIMARY KEY , Category VARCHAR(255)  )")
cursor.execute("CREATE TABLE IF NOT EXISTS tags_category (Category_Id INT , Tag_Id INT  ,FOREIGN KEY (Tag_Id) REFERENCES tags(Tag_Id))")
cursor.execute("CREATE TABLE IF NOT EXISTS languages (Language_Id INT PRIMARY KEY , Language VARCHAR(255) )")
cursor.execute("CREATE TABLE IF NOT EXISTS forks_and_stars (Symbol varchar(60) PRIMARY KEY , Forks VARCHAR(60) ,Stars VARCHAR(60),FOREIGN KEY (Symbol) REFERENCES coins200(Symbol) )")
cursor.execute("CREATE TABLE IF NOT EXISTS coins_languages (Symbol varchar(60)  , Language_Id INT ,Percentage VARCHAR(60),FOREIGN KEY (Symbol) REFERENCES coins200(Symbol) )")
print('__ Done !')

__ Done !

In [23]:
cursor.execute("ALTER TABLE coin_tags ADD CONSTRAINT tags FOREIGN KEY (Tag_Id) REFERENCES tags(Tag_Id)")
cursor.execute("ALTER TABLE tags_category ADD CONSTRAINT category FOREIGN KEY (Category_Id) REFERENCES category(Category_Id)")

cursor.execute("ALTER TABLE coins_languages ADD CONSTRAINT languages FOREIGN KEY (Language_Id) REFERENCES languages(Language_Id)")
print("done!")

done!

In [6]:
#clean up database if it is nesseccery
cursor.execute("DROP DATABASE %s" % my_database)